# Chapter 1

In [1]:
# This dataset is include the top cited papers in machine learning.
# title|summary|authors|year
# You can read more on https://www.doradolist.com/papers/21-most-cited-machine-learning-papers
# Create by A.Nazari for nlp tasks

### Boolean retrieval

### inverted index

### AND (intersect), OR (union), AND NOT (difference) 

In [2]:
# Open file and create vocab
vocab = []
docs = []
filename = "21-most-cited-machine-learning-papers_titles.txt"

with open(filename, encoding='utf-8') as f:
    lines = f.readlines()
    for line in lines:
        # Word tokenization 

        title = line.split("|")[0].lower()
        docs.append(title)
        for word in title.split():
            if word not in vocab:
                vocab.append(word)


print(len(vocab), "\n", vocab,"\n", len(docs), "\n", docs)

85 
 ['deep', 'residual', 'learning', 'for', 'image', 'recognition', 'adam:', 'a', 'method', 'stochastic', 'optimization', 'imagenet', 'classification', 'with', 'convolutional', 'neural', 'networks', 'random', 'forests', 'very', 'large-scale', 'scikit-learn:', 'machine', 'in', 'python', 'support-vector', 'generative', 'adversarial', 'nets', 'faster', 'r-cnn:', 'towards', 'real-time', 'object', 'detection', 'region', 'proposal', 'libsvm:', 'library', 'support', 'vector', 'machines', 'gradient-based', 'applied', 'to', 'document', 'imagenet:', 'hierarchical', 'database', 'going', 'deeper', 'convolutions', 'latent', 'dirichlet', 'allocation', 'batch', 'normalization:', 'accelerating', 'network', 'training', 'by', 'reducing', 'internal', 'covariate', 'shift', 'tensorflow:', 'system', 'dropout:', 'simple', 'way', 'prevent', 'from', 'overfitting', 'large', 'scale', 'visual', 'challenge', 'mapreduce:', 'simplified', 'data', 'processing', 'on', 'clusters', 'bagging', 'predictors'] 
 21 
 ['deep

In [3]:
# term-document matrix
import numpy as np
V = len(vocab)
D = len(docs)
matrix = np.zeros((V, D))

for term_id, term in enumerate(vocab):
    for doc_id, doc in enumerate(docs):
        if term in doc:
            matrix[term_id, doc_id] = 1


print(matrix)

[[1. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [31]:
query =  "Deep learning"

# Query representation
query_terms = query.lower().split()
query_representation = [matrix[vocab.index(i),:] for i in query_terms]

oprator = "and" # and/or
if oprator == "and":
    relevate_docs_idx = np.ones(D)
else: 
    relevate_docs_idx = np.zeros(D)
    
for rep in query_representation:
    if oprator == "and":
        relevate_docs_idx = np.logical_and(relevate_docs_idx, rep)
    else:
        relevate_docs_idx = np.logical_or(relevate_docs_idx, rep)


relevate_docs = [docs[i] for i in np.where(relevate_docs_idx== True)[0]]
for doc in relevate_docs:
    print(doc)



deep residual learning for image recognition


In [5]:
# inverted index
inverted_index = {}

for term_id, term in enumerate(vocab):
    for doc_id, doc in enumerate(docs):
        if term in doc:
            if term in inverted_index.keys():
                inverted_index[term] = inverted_index[term] + [doc_id]
            else:
                inverted_index[term] = [doc_id]


print(inverted_index)

{'deep': [0, 2, 4, 6, 13, 15], 'residual': [0], 'learning': [0, 5, 6, 11, 16], 'for': [0, 1, 3, 4, 10, 16], 'image': [0, 2, 4, 12, 18], 'recognition': [0, 4, 11, 18], 'adam:': [1], 'a': [0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20], 'method': [1], 'stochastic': [1], 'optimization': [1], 'imagenet': [2, 12, 18], 'classification': [2], 'with': [2, 9, 13], 'convolutional': [2, 4], 'neural': [2, 17], 'networks': [2, 4, 7, 9, 17], 'random': [3], 'forests': [3], 'very': [4], 'large-scale': [4, 12, 16], 'scikit-learn:': [5], 'machine': [5, 10, 16], 'in': [0, 5, 6, 10, 11, 13, 15, 16, 17, 19, 20], 'python': [5], 'support-vector': [7], 'generative': [8], 'adversarial': [8], 'nets': [8], 'faster': [9], 'r-cnn:': [9], 'towards': [9], 'real-time': [9], 'object': [9], 'detection': [9], 'region': [9], 'proposal': [9], 'libsvm:': [10], 'library': [10], 'support': [7, 10], 'vector': [7, 10], 'machines': [10], 'gradient-based': [11], 'applied': [11], 'to': [1, 7, 9, 10, 11, 17, 20

In [32]:
# intersect
def intersect(p, q):
    intersect_list = []
    i = j = 0
    while (i<len(p) and j<len(q)):
        if (p[i] == q[j]):
            intersect_list.append(p[i])
            i+=1
            j+=1
        elif p[i]<q[j]:
            i+=1
        else:
            j+=1
    
    return intersect_list

intersect([1,2,3,4,5],[1,3,5,7,9])

[1, 3, 5]

In [29]:
query =  "Deep learning image"

# Query preprocessing
query_terms = query.lower().split()

relevate_docs_idx = inverted_index[query_terms[0]]
for idx in range(1, len(query_terms)):
    relevate_docs_idx = intersect(relevate_docs_idx, inverted_index[query_terms[idx]])

print(relevate_docs_idx)
relevate_docs = [docs[i] for i in relevate_docs_idx]
for doc in relevate_docs:
    print(doc)

[0]
deep residual learning for image recognition


In [39]:
def union(p, q):
    i = j = 0
    union_list = []

    while i < len(p) and j < len(q):
        if p[i] < q[j]:
            union_list.append(p[i])
            i += 1
        elif p[i] > q[j]:
            union_list.append(q[j])
            j += 1
        else:
            union_list.append(p[i])
            i += 1
            j += 1

    # Add remaining elements of list1
    while i < len(p):
        union_list.append(p[i])
        i += 1

    # Add remaining elements of list2
    while j < len(q):
        union_list.append(q[j])
        j += 1

    return union_list

union([1,2,3,4,5],[1,3,5,7,9])

[1, 2, 3, 4, 5, 7, 9]

In [40]:
def difference(p, q):

    i, j = 0, 0
    difference_list = []

    while i < len(p) and j < len(q):
        if p[i] < q[j]:
            difference_list.append(p[i])
            i += 1
        elif p[i] > q[j]:
            j += 1
        else:
            i += 1
            j += 1

    # Add remaining elements of p
    while i < len(p):
        difference_list.append(p[i])
        i += 1

    return difference_list

difference([1,2,3,4,5],[1,3,5,7,9])

[2, 4]

### Homework

In [ ]:
# Homework 1:
# Implement the optimal operation

# Homework 2:
# Apply the following queries using the above functions. 

# 1. Deep and (Not Learning)
# 2. Deep or Learning
# 3. (Deep and (Not Learning)) or image

# Homework 3:
# In the context of Boolean retrieval, consider a document collection with the following terms appearing in the documents:

# Document 1: "cat sat on the mat"
# Document 2: "the dog chased the cat"
# Document 3: "the mat was on the floor"

# Using Boolean retrieval, what would be the result of the query: cat AND (mat OR floor)?
# Explain the steps involved in processing this query and list the documents that would be retrieved.